apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongo-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-test-deployment
  template:
    metadata:
      labels:
        app: mongodb-pod
    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongodb-pod
  ports:
    - port: 8080
      targetPort: 27017
